### ISSUE TITLE
Issue With MLG.tv

### ISSUE THREAD

**Issue by ishting** [chrippa/livestreamer#748]
I used to watch MLG streams with livestreamer and VLC player but haven't been able to get it to work since I formatted my laptop. This is the error I get

http://i.imgur.com/I75iM0e.png

Twitch streams are working fine it seems.

**Comment by chrippa** [comment]
I believe this issue has been fixed, but not put out in a release yet. Please try the [nightly build](http://docs.livestreamer.io/install.html#nightly-build).

**Comment by Uiharu** [comment]
If I update to the nightly build will I still get the update notification whenever the next stable build is released?

**Comment by KaDe-** [comment]
How do i upgrade to the nightly build? Extremely confused!

**Comment by chrippa** [comment]
1.12.0 is now out and should fix all issues. 

> How do i upgrade to the nightly build? Extremely confused!

The nightly build is just a zip file containing Livestreamer, just extract it and use.

> If I update to the nightly build will I still get the update notification whenever the next stable build is released?

Yes.
